services:
  mongo:
    image: mongo
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  server:
    build: ./server
    container_name: server_c
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment: 
      - WATCHPACK_POLLING=true
      - START_CMD=npx nodemon index.js
    stdin_open: true
    tty: true
  client:
    build: ./client
    container_name: client_c
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
volumes:
  mongo-data: