FROM node:22.12.0-alpine

WORKDIR /app

# RUN apk update && apk add build-base g++ cairo-dev pango-dev giflib-dev libc6-compat libjpeg-turbo
RUN apk add --update --no-cache \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev \
    libtool \
    autoconf \
    automake \
    libc6-compat

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "${START_CMD:-node index.js}"]