FROM node:22.12.0-alpine

WORKDIR /app

COPY package.json .

RUN apk update && apk add build-base g++ cairo-dev pango-dev giflib-dev

RUN npm install

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "${START_CMD:-node index.js}"]