#!/bin/sh

echo "Which container would you like to stop? "
echo "Options:"
eval ls ../*.yml | sed 's|../compose-\(.*\)\.yml|\1|'

read container

flags=''
#!/bin/sh
read -r -p "Also build? [y/N] " response
if [ "$response" = "yes" ] || [ "$response" = "y" ]; 
then
    flags='--build'
fi

eval docker compose -f ../compose-$container.yml up $flags

echo "Attempting to start compose-$container.yml with $flags" 