#!/bin/sh

echo "Which container would you like to stop? "
echo "Options:"
eval ls ../*.yml | sed 's|../compose-\(.*\)\.yml|\1|'

read container


#!/bin/sh
read -r -p "Also remove containers? [y/N] " response
if [ "$response" = "yes" ] || [ "$response" = "y" ]; 
then
    command='down'
else
    command='stop'
fi

eval docker compose -f ../compose-$container.yml $command

echo "Attempting to $command compose-$container.yml" 